### ISSUE TITLE
MacOS: NoSuchMethodError with 1.0.3

### ISSUE THREAD

**Issue by cheeseng** [javaaiorg/stable-diffusion.java#2]
The error didn't happen with previous version, but the latest version 1.0.3 encountered problem when runs on MacOS, tested with both jdk 17 and 22,  attached the core dump of the crash: 

[hs_err_pid3748.log](https://github.com/javaaiorg/stable-diffusion.java/files/14900294/hs_err_pid3748.log)

Perhaps problem with the embedded native lib for mac?

**Comment by javaaiorg** [comment]
Fixed, wait for a few hours, after maven central updates, you will beable to use latest version v1.0.4. 

That's the latest version test logs on macos platform: 

u@udeMac build % java -jar StableDiffusionConsole-1.0.3.jar
Using CPU backend
loading model from '/Users/u/Desktop/models/sd-v1-4.ckpt'
load /Users/u/Desktop/models/sd-v1-4.ckpt using checkpoint format
init from '/Users/u/Desktop/models/sd-v1-4.ckpt'
Stable Diffusion 1.x 
Stable Diffusion weight type: f32
loading vocab
vocab size: 49408
ggml tensor size = 416 bytes
clip params backend buffer size =  470.66 MB (449 tensors)
unet params backend buffer size =  2165.24 MB (720 tensors)
vae params backend buffer size =  179.03 MB (328 tensors)
preparing memory for the weights
loading weights
loading tensors from /Users/u/Desktop/models/sd-v1-4.ckpt
model size = 2784.45MB
total memory buffer size = 2814.93MB (clip 470.66MB, unet 2165.24MB, vae 179.03MB)
loading model from '/Users/u/Desktop/models/sd-v1-4.ckpt' completed, taking 14.99s
running in eps-prediction mode
finished loaded file
load:true
prompt after extract and remove lora: "test"
apply_loras completed, taking 0.00s
parse 'test' to [['test', 1], ]
split prompt "test" to tokens ["test</w>", ]
learned condition compute buffer size: 2.58 MB
computing condition graph completed, taking 96 ms
parse '' to [['', 1], ]
split prompt "" to tokens []
learned condition compute buffer size: 2.58 MB
computing condition graph completed, taking 89 ms
get_learned_condition completed, taking 187 ms
sampling using Euler A method
generating image: 1/1 - seed 42
diffusion compute buffer size: 552.28 MB
  |>                                                 | 0/20 - 0.00it/s
  |==>                                               | 1/20 - 21.48s/it

**Comment by cheeseng** [comment]
@javaaiorg  Works perfectly, thanks for fixing it!

**Comment by cheeseng** [comment]
@javaaiorg Weird, I am using 1.0.4 and seems like the problem is back again, I see NoSuchMethodError again in the dump file after the program crashed.

**Comment by javaaiorg** [comment]
![macos-test-jdk8](https://github.com/javaaiorg/stable-diffusion.java/assets/143949784/c546b5f4-c33c-4662-9409-14e1ab30ee35)
I have tested it on jdk8 and jdk11, and the image can be generated successfully. Can you give me your call stack? And tell me the jdk version you are using?

**Comment by cheeseng** [comment]
@javaaiorg Sure, I am using jdk17 and here's the log file: 

[hs_err_pid18921.log](https://github.com/user-attachments/files/15755542/hs_err_pid18921.log)

**Comment by cheeseng** [comment]
@javaaiorg If it helps, I am running on Sonoma 14.5.
